/** Claves opcionales en `BusinessRule.ruleKey` (valores por defecto en código si no existen). */
export const QUOTE_BUSINESS_RULE_KEYS = {
  RISK_INSURANCE_DAILY: 'QUOTE_RISK_INSURANCE_DAILY',
  FUEL_FEE: 'QUOTE_FUEL_FEE',
  AIRPORT_FEE: 'QUOTE_AIRPORT_FEE',
  TRANSFER_FEE: 'QUOTE_TRANSFER_FEE',
  SEASON_HIGH_CODE_PATTERNS: 'QUOTE_SEASON_HIGH_CODE_PATTERNS',
  SEASON_EXTREME_CODE_PATTERNS: 'QUOTE_SEASON_EXTREME_CODE_PATTERNS',
} as const;

export const AGENCY_PRICING_KEYS = {
  MIN_DAYS_OVERRIDE: 'QUOTE_MIN_DAYS_OVERRIDE',
} as const;

export const DEFAULT_HIGH_SEASON_CODE_SUBSTRINGS = ['ALTA', 'HIGH', 'MEDIA_ALTA'];
export const DEFAULT_EXTREME_SEASON_CODE_SUBSTRINGS = ['EXTREMA', 'EXTREME', 'PEAK'];
